// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.1

package types

type AddReq struct {
	Book  string `json:"book"`
	Price int64  `json:"price"`
}

type AddResp struct {
	Ok bool `json:"ok"`
}

type CheckReq struct {
	Book string `form:"book"`
}

type CheckResp struct {
	Found bool  `json:"found"`
	Price int64 `json:"price"`
}

type UpdateBookPriceReq struct {
	BookId uint64 `json:"book_id"`
	Price  uint64 `json:"price"`
}

type UpdateBookResp struct {
	BookId   uint64 `json:"book_id"`
	BookName string `json:"book_name"`
}
