// Code generated by goctl. DO NOT EDIT.
// goctl 1.8.2

package types

type AddBook struct {
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

type BatchAddReq struct {
	Books AddBook `json:"books"`
}

type BatchAddResp struct {
	Ids []int64 `json:"ids"`
}

type Book struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Price int64  `json:"price"`
}

type GetBookListReq struct {
	Ids []int64 `json:"ids"`
}

type GetBookListResp struct {
	BookList Book `json:"list"`
}

type AddReq struct {
	Book AddBook `json:"book"`
}

type AddResp struct {
	Ok bool `json:"ok"`
}

type CheckReq struct {
	Book string `josn:"book"`
}

type CheckResp struct {
	Found bool  `json:"found"`
	Price int64 `json:"price"`
}

type UpdateBookPriceReq struct {
	BookId uint64 `json:"book_id"`
	Price  uint64 `json:"price"`
}

type UpdateBookResp struct {
	BookId   uint64 `json:"book_id"`
	BookName string `json:"book_name"`
}
